### ISSUE TITLE
Update Python Packages to Latest Version

### ISSUE THREAD

**Issue by xrebel1** [dreamnettech/dreampower#102]
Update the python packages to latest versions. 

1. Python 3.8.6
2. pip==20.2.4 https://pypi.org/project/pip/
3. pyinstaller==4.0 https://pypi.org/project/pyinstaller/
4. numpy==1.19.2 https://pypi.org/project/numpy/
5. opencv-python==4.4.0.44 https://pypi.org/project/opencv-python/
6. pillow==8.0.1 https://pypi.org/project/Pillow/
7. torch==1.6.0 https://pypi.org/project/torch/
8. torchvision==0.7.0 https://pypi.org/project/torchvision/
9. torch & torchvision Nightly (OPTIONAL)
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

In the following files.
1. build-release.yml
2. build.yml  
2. requirements.txt
3. requirements-cpu.txt
4. requirements-gpu.txt

I will update the list when a new update is available.

**Comment by nullablebool** [comment]
+1 I've just tested the pytorch nightly builds on Win10 Python 3.8 and it seems to work fine and supports RTX3080.

**Comment by xrebel1** [comment]
You are the developer of DreamPower, right? So, you have to do the necessary maintenance in order to keep the components up to date to the latest version.

**Comment by xrebel1** [comment]
Latest versions of these components drop the RAM usage to 2 GB maximum for a 512x512 image. So, it's a massive drop in required RAM. Update the components asap.
