### ISSUE TITLE
The download quota for this file has been exceeded.

### ISSUE THREAD

**Issue by SpotBR** [dreamnettech/dreampower#103]
On checkpoint download:
https://downloads.dreamnet.tech/checkpoints/v0.0.1?direct=1
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "downloadQuotaExceeded",
    "message": "The download quota for this file has been exceeded."
   }
  ],
  "code": 403,
  "message": "The download quota for this file has been exceeded."
 }
}

**Comment by kolessios** [comment]
Thanks for the report but this problem only happens temporarily, every 15 minutes our server checks the down links and removes them from being used.

**Comment by SpotBR** [comment]
how can i delete this issue for people don't see me here?
