### ISSUE TITLE
Tool for making Masks

### ISSUE THREAD

**Issue by ayushrox** [dreamnettech/dreampower#104]
Can you please provide the tool or link to the tool we should use to create custom masks?

**Comment by kolessios** [comment]
Sorry but there is no tool that specializes in creating masks, the closest thing is [DreamTime](https://dreamtime.tech) although it only helps you with organization. You can get information about Custom masks in the [DreamTime guide](https://dreamtime.tech/docs/guide/custom-masks) although keep in mind that it has many references to the application.
