### ISSUE TITLE
[MacOS] libiomp5.dylib is damaged. DreamPower won't run!

### ISSUE THREAD

**Issue by wyv3rnnn** [dreamnettech/dreampower#114]
**Describe the bug**
"libiomp5.dylib" is damaged. In the terminal there's also this error:
`ImportError: dlopen(/Users/REDACTED/Downloads/DreamPower/torch/_C.cpython-38-darwin.so, 2): Library not loaded: @loader_path/libiomp5.dylib`

  `Referenced from: /Users/REDACTED/Downloads/DreamPower/libtorch_python.dylib
  Reason: no suitable image found.`

 `Did find:
	/Users/REDACTED/Downloads/DreamPower/torch/../libiomp5.dylib: code signature in (/Users/REDACTED/Downloads/DreamPower/torch/../libiomp5.dylib) not valid for use in process using Library Validation: library load disallowed by system policy`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to DreamPower's folder.
2. Run ./dreampower in your terminal on MacOS Catalina
3. Wait for 10 seconds
4. See error.

**Expected behaviour**
The help menu is supposed to show up in the terminal.

**Screenshots**
<img width="428" alt="Screen Shot 2021-04-03 at 10 40 42 PM" src="https://user-images.githubusercontent.com/77228062/113497046-d2c0f680-94cd-11eb-8567-8af56c8183fe.png">

**Enviroment (please complete the following information):**
 - Version: 1.3.0
 - OS: MacOS Catalina v10.15.6 (19G73)

**Additional context**
I have tried to delete and download the archive from the releases page twice but both times it won't work. Any help would be much appreciated! Thanks!!

**Comment by kolessios** [comment]
Technically it's not a bug, it's about macOS strict security policies. I don't know much about the operating system but the quickest way I can find to bypass these messages is to run the command:

`sudo spctl --master-disable`

Note that this command disables these policies so in theory your computer will be less protected. You can get more information about it in [this article](https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave).
