### ISSUE TITLE
failed transformation from new update how to fix ?

### ISSUE THREAD

**Issue by cupcakejunki3** [dreamnettech/dreampower#71]
Transformation #1 failed
The process has been interrupted by an unknown error, this may be caused by a corrupt installation, please check the console for more information.

For more information please take a screenshot and report the following on Github or here:

        Error: usage: dreampower [-h] [-d] [-v] {run,checkpoints,gpu-info,daemon} ...
dreampower: error: argument mode: invalid choice: 'D:\Users\psych\AppData\Local\Programs\DreamTime\cli/624195e5-84cc-44f0-86a2-0b2cafb22a40.png' (choose from 'run', 'checkpoints', 'gpu-info', 'daemon')

usage: dreampower [-h] [-d] [-v] {run,checkpoints,gpu-info,daemon} ... dreampower: error: argument mode: invalid choice: 'D:\Users\psych\AppData\Local\Programs\DreamTime\cli/624195e5-84cc-44f0-86a2-0b2cafb22a40.png' (choose from 'run', 'checkpoints', 'gpu-info', 'daemon')

**Comment by deeppppp** [comment]
DreamTime v1.1.0 and DreamPower v1.2.x are not compatible.
Please wait for DreamTime v.1.2.x to become available.
