### ISSUE TITLE
Error Checkpoints

### ISSUE THREAD

**Issue by dpatrongomez** [dreamnettech/dreampower#72]
`ubuntu@ubuntu-VirtualBox:~/Documentos/dreampower-master$ python3 main.py checkpoints download`
`[INFO] Downloading https://cdn.dreamnet.tech/releases/checkpoints/v0.0.1.zip`
`[INFO] Extracting /tmp/tmp6bebckp4/v0.0.1.zip      `                             
`[ERROR] stat: path should be string, bytes, os.PathLike or integer, not dict`
`[ERROR] Something Gone Bad Download Downloading The Checkpoints`

**Comment by deeppppp** [comment]
Thank you for reporting the issue.
Updated code with a fix has been pushed to the canary branch and will be included in the upcoming minor release.
