### ISSUE TITLE
Can't  start with windows 10

### ISSUE THREAD

**Issue by wenx123** [dreamnettech/dreampower#73]
As the title,  can not start with win 10 from v1.2.0 to v1.2.2. But Ok with  v1.1.0 at the same PC.Do I  need any other  programs ?

**Comment by deeppppp** [comment]
Can you provide a screenshot?

**Comment by wenx123** [comment]
![20191107_123034](https://user-images.githubusercontent.com/53502673/68360333-9c593d80-015a-11ea-836d-3c509d932a8b.jpg)

**Comment by wenx123** [comment]
Like this, start and no effect.

**Comment by HWiese1980** [comment]
The usage is literally described below the command. Dream**Power** is the CLI, not the UI. If you was expecting a UI, that's Dream**Time**.

**Comment by wenx123** [comment]
Got  it. Thanks a lot !
