### ISSUE TITLE
`GLIBC_2.25' not found

### ISSUE THREAD

**Issue by cerebrix92** [dreamnettech/dreampower#74]
**Describe the bug**
[6983] Error loading Python lib '/media/pixiepox/ssd_storage/DreamPower/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /media/pixiepox/ssd_storage/DreamPower/libpython3.7m.so.1.0)

**To Reproduce**
1. I am currently on DeepinOS 15.11
2. Whatever command I try to run is met with this error.
3. PS - I tried the software on Ubuntu and Mint previously and it worked 100% fine.

**Screenshots**
![DeepinScreenshot_20191112141440](https://user-images.githubusercontent.com/42859799/68655878-d3629100-0556-11ea-854e-34bed3824777.png)

**Enviroment (please complete the following information):**
 - Version [1.2.2]
 - OS: [DeepinOS]

**Comment by deeppppp** [comment]
Can you try:
1) make a back-up of the file: '/media/pixiepox/ssd_storage/DreamPower/libpython3.7m.so.1.0
2) remove the file:  '/media/pixiepox/ssd_storage/DreamPower/libpython3.7m.so.1.0

The idea is that your OS comes with the library already and the above should make it use that library instead of the one included in the dreampower package.

if that throws an error that the library can't be found, then restore the file.
and report back here :)

**Comment by cerebrix92** [comment]
I made backup of the above mentioned file and deleted it from the DreamPower folder. I ran the basic run command again but was met with another error. Attaching screenshots.

![DeepinScreenshot_20191113154655](https://user-images.githubusercontent.com/42859799/68754596-fe1f1900-062c-11ea-8ec9-5d2fb7fcb434.png)

Thank you for responding (^_^)

**Comment by deeppppp** [comment]
can you try installing python 3.7?
you can also join our chat:
https://chat.dreamnet.tech/
making solving this issue a bit easier :)

**Comment by cerebrix92** [comment]
I am sorry, but I can't figure out how to install the latest python on linux. God, it was just simple installer on Windows. I found out that DeepinOS ships with python 3.5. I am searching and reading articles on how to install the latest python. Will report back once I do. Thank you and sorry for my incompetence.

**Comment by cerebrix92** [comment]
I am sorry, I couldn't figure out if I had successfully installed the latest python. I tried many guides from the internet but my results weren't exactly what they mentioned it would be. Nevertheless, I couldn't get dreampower to work. It kept throwing the same error.

I ended up distro hopping back to Ubuntu now. Everything works as it should. Thank you guys and you can close the issue if you want.

**Comment by deeppppp** [comment]
ok, glad to hear it works now.
