### ISSUE TITLE
Checkpoint download problem

### ISSUE THREAD

**Issue by devilemperor** [dreamnettech/dreampower#76]
Hello,

When I try to use:
`dreampower checkpoints download`
I get that error:

> Downloading https://cdn.dreamnet.tech/releases/checkpoints/v0.0.1.zip
> [INFO] Extracting C:\Users\user\AppData\Local\Temp\tmpbf5e3x1e\v0.0.1.zip
> [ERROR] stat: path should be string, bytes, os.PathLike or integer, not dict
> [ERROR] Something Gone Bad Download Downloading The Checkpoints

**Enviroment:**
 - Version 1.2.2
 - OS: Windows 10 1909

Thanks.

**Comment by deeppppp** [comment]
fixed in canary branch, will be part of next minor release.
