### ISSUE TITLE
File not supported format for extension in capital letters

### ISSUE THREAD

**Issue by user42de** [dreamnettech/dreampower#81]
**Describe the bug**
If you try to process an image with an extension written in capital letters (e.g. image.JPG) dreampower says the file format is not supported. If the name is changed to image.jpg it works fine again.

**To Reproduce**
1. Take image name.JPG
2. Process
3. Get error

**Expected behavior**
Checking of extension should be case-insensitive

**Enviroment (please complete the following information):**
 - DreamPower Version 1.2.3
 - OS: Win10

**Comment by deeppppp** [comment]
added a fix in canary branch, until it's deployed you can rename the file name to lowercase.
