### ISSUE TITLE
Color Correction Algorithm Is Influenced by Removed Garments

### ISSUE THREAD

**Issue by chicagotaco** [dreamnettech/dreampower#82]
**Describe the bug**
When using the color correction option, the subject of the transformation will be corrected to match the color of the removed garments. For example, the skin of a person wearing a red shirt would turn red after the transformation.

**To Reproduce**
1. Turn on color correction
2. Perform a transformation on an image with a colorful shirt
3. See error

**Expected behavior**
The skin tone to match the original image when using color correction

**Screenshots**
![P0](https://user-images.githubusercontent.com/54223585/69920135-12ac3f80-147c-11ea-900e-9433ec27eee5.jpg)
![ec1](https://user-images.githubusercontent.com/54223585/69920178-a8e06580-147c-11ea-979b-5cad5dceecdb.png)

**Enviroment (please complete the following information):**
 - Dreamtime 1.2.1
 - OS: Windows 10 1903

**Additional context**
This is just conjecture and I haven't actually examined how the algorithm functions, perhaps this issue could be fixed via setting the parts of the image identified as clothes to transparent in both the before and after images before feeding them into the color correction algorithm, then using the difference in hue to modify the original output,

**Comment by deeppppp** [comment]
The color correction is a 3rd party algorithm that takes everything from the input image.
It's a stop-gap solution until the new checkpoints are trained up that do not have the color issues.
