### ISSUE TITLE
Dreampower does not find checkpoints when run outside of its directory

### ISSUE THREAD

**Issue by jochemstoel** [dreamnettech/dreampower#83]
I have added the folder c:\dreampower to my Windows PATH environment variable so that I can type dreampower in the CLI from anywhere. However it throws the error that the checkpoints can not be found and need to be downloaded. I believe this is a bug.

**To Reproduce**
1. Download DreamPower prebuilt v1.2.3 for Windows (GPU)
2. Extract it and add the folder to your Windows PATH environment variable
3. Go to some other folder like desktop and type dreampower

**Expected behavior**
It should find the checkpoints relative to itself and not the current process directory. (cwd) However it should not look for the input image itself in its own directory. The whole point is that I can run this in another folder.

**Enviroment**
 - Version [1.2.3]
 - OS: [e.g. Windows 10 1803]

**Additional context**
v1.0.0 works fine.

**Comment by deeppppp** [comment]
use the -c parameter to indicate the folder the checkpoints are located if not in the default location of ./checkpoints
