### ISSUE TITLE
Support for B&W

### ISSUE THREAD

**Issue by danngalann** [dreamnettech/dreampower#84]
**Describe the feature you'd like**
It is fashion nowadays to take B&W pictures, apparently. And this software, great as it is, can come up with some REALLY WEIRD outputs for B&W. I think it would be great to have this feature, as you could use the same dataset with a B&W filter. A B&W "mode" on DreamTime would also be faster (i think) since there are less channels to process.

**Comment by deeppppp** [comment]
Models are trained on color images, and the algorithm uses colored masks in the process.
Getting the algo to work for B&W pictures would need a different approach to the algorithm and won't be implemented in the short term.
