### ISSUE TITLE
Can’t reach 100% CPU load

### ISSUE THREAD

**Issue by zoenagy235** [dreamnettech/dreampower#90]
Can’t reach 100% CPU load neither with these: --n-cores=2, 4, 8
Even selected 8cores only goes up to 53% CPU load peak (33% average).
No SSD operation is happening at that time. 

Which means wasting time by not fully utilizing the CPU.
Is there a bottleneck in the code?

**To Reproduce**
Simple run: --auto-resize --n-cores=4  (no CUDA)

**Enviroment (please complete the following information):**
PC: intel i5 Windows 10 x64 (2cores, 4 logical CPUs)
Python 3.6.7
latest SW checkpoint

**Comment by kolessios** [comment]
Sorry for the late reply, the `--n_cores` parameter is used only in two processes:

- To process several frames at the same time for gif and video.
- To process OpenCV masks (Small usage)

So it is normal that the CPU usage is low, the important part of the algorithm (GAN) does not support multi threading for now.
