### ISSUE TITLE
Green result

### ISSUE THREAD

**Issue by zoenagy235** [dreamnettech/dreampower#92]
The attached image generates green boobs.
How to prevent this?
Does the input file need color adjustment?
Can't imagine better pose than this.
![i2](https://user-images.githubusercontent.com/63315823/78940503-dc2ba480-7aad-11ea-8863-74d4ccc78040.jpg)
![i2_](https://user-images.githubusercontent.com/63315823/78940567-f82f4600-7aad-11ea-8542-e09397addd7a.jpg)

Using latest release, CPU only mode.

**Comment by zoenagy235** [comment]
Is there somewhere a checklist of input requirements/suggestions to get the best output?

**Comment by xrebel1** [comment]
The issue is the white background/padding left and right of the photo that produces color distortion. Try these photos I have already tested them.
![1](https://user-images.githubusercontent.com/59066195/79011298-6a666000-7b6c-11ea-8d4c-f8d4c202316f.png)
![2](https://user-images.githubusercontent.com/59066195/79011308-705c4100-7b6c-11ea-996b-8960aba7700b.png)
![4](https://user-images.githubusercontent.com/59066195/79011317-7520f500-7b6c-11ea-8e9f-71592b35db16.png)

**Comment by zoenagy235** [comment]
That makes sense, white contains every color.
Should I enlarge smaller images to fit 512x512, or it's better to just pad it out and keep original size?

**Comment by xrebel1** [comment]
This is the way I do it. I have made four 512x512 backgrounds 1. white-black 2. black-white 3. white 4. black. In Photoshop I resize (crop or enlarge) the photo I want to transform to ...x512, copy it and paste it on top of these four backgrounds. Then I run the four photos in DreamTime and I compare the results. It is known that the mixed (1st and 2nd) backgrounds eliminate the color distortion but can run the solid white and the solid black as well. I give you the backgrounds. When you have the transformed photo that you like you can enlarge it.
![1](https://user-images.githubusercontent.com/59066195/79014291-41959900-7b73-11ea-8f4c-a7aa1028f64c.png)
![2](https://user-images.githubusercontent.com/59066195/79014294-43f7f300-7b73-11ea-9ee2-03c9054e0cfe.png)
![3](https://user-images.githubusercontent.com/59066195/79014298-45c1b680-7b73-11ea-8609-2d66d5c66f2a.png)
![4](https://user-images.githubusercontent.com/59066195/79014303-49553d80-7b73-11ea-9d06-bb21916a9718.png)

**Comment by xrebel1** [comment]
Also, you can check here https://www.pornhub.com/album/54247352 some of the photos I created using DreamPower and custom masks,

**Comment by zoenagy235** [comment]
Great idea, I will try out the mixed option!

Any suggestion regarding the image content? 
Like increasing/decreasing saturation/sharpness or other adjustment that improves result?

**Comment by xrebel1** [comment]
Mixed backgrounds eliminate color distortion so you don't have to make any other adjustments. They are 256x512 black and white put together. As I said before this method works only for non-square original photos, so the background left and right is visible, like the photo you posted in your first comment.

**Comment by zoenagy235** [comment]
thank you!
