### ISSUE TITLE
Something Gone Bad Download Downloading The Checkpoints

### ISSUE THREAD

**Issue by dontbanmeplz** [dreamnettech/dreampower#99]
**Describe the bug**
The checkpoints are missing

**To Reproduce**
1. Run './dreampower checkpoints download'
2. See error

**Expected behavior**
idk i have never runit

**Enviroment (please complete the following information):**
 - DreamTime Version [e.g. 1.4.0]
 - OS: [ubuntu]
 - RAM: [4GB]
 - GPU: [n/a]

**Comment by kolessios** [comment]
Sorry for the problem, for now download the checkpoints manually at:
https://downloads.dreamnet.tech/checkpoints/v0.0.1

**Comment by dontbanmeplz** [comment]
k thx

**Comment by dark3128** [comment]
Hi, I have the same problem:

[INFO] Downloading https://downloads.dreamnet.tech/checkpoints/v0.0.1?direct=1
[INFO] Extracting /tmp/tmpnzwz8cih/v0.0.1.zip
[ERROR] File is not a zip file
[ERROR] Something Gone Bad Download Downloading The Checkpoints

**Comment by dark3128** [comment]
I just fixed it by downloading the zip from github.
